title: The Representatives of Monkey Jack
email: representingmonkeyjack@gmail.com
description: >
  Monkey Jack is a funky mamma jamma
minima:
  social_links:
    twitter: repsmonkeyjack
    github: repsmonkeyjack
    instagram: repsmonkeyjack
    bandcamp: repsmonkeyjack
    backstagepro: repsmonkeyjack
    linktree: repsmonkeyjack
    facebook: repsmonkeyjack

markdown: kramdown

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
 
